# render.yaml
# This is the blueprint for deploying our ATS Resume Agent on Render.

services:
  # A Web Service for our Streamlit application
  - type: web
    name: ats-resume-agent
    # Use the 'docker' runtime to build from our Dockerfile
    runtime: docker
    # The branch to deploy from (e.g., main, master)
    branch: main
    # Render will automatically build the Dockerfile in the root of the repo.
    # We don't need to specify the Dockerfile path unless it's in a different location.

    # Health Check Configuration
    # Streamlit apps don't have a standard /healthz endpoint.
    # Render's default TCP health check is usually sufficient. It just checks if the port is open.
    # We can give it a bit more time to start up if needed.
    healthCheckPath: /
    initialDeployHook: sleep 30 # Give it a few seconds to start before first health check

    # Environment Variables for Secrets
    # We will create an Environment Group on the Render dashboard for our secrets.
    envVars:
      - fromGroup: ats-agent-secrets