import pytest
from docx import Document
from io import BytesIO
import sys
import os

# Add the project root to the Python path to allow imports
# This is the same trick we used in app.py
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from utils import txt_to_docx_bytes

def test_txt_to_docx_bytes_creates_valid_docx():
    """
    Tests if the function returns bytes that can be opened as a DOCX file.
    """
    test_text = "Hello World\nThis is a test."
    docx_bytes = txt_to_docx_bytes(test_text)
    
    # Assert that the output is of type bytes
    assert isinstance(docx_bytes, bytes)
    
    # Assert that the bytes are not empty
    assert len(docx_bytes) > 0
    
    # Try to open the bytes as a Document to check for validity
    try:
        doc = Document(BytesIO(docx_bytes))
        assert len(doc.paragraphs) > 0
    except Exception as e:
        pytest.fail(f"Could not open the generated bytes as a DOCX file: {e}")
